<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>FlexSlider Widget : Thumbnail navigation 1</title>
<script type='text/javascript' src='js/vendor/modernizr-2.6.2-respond-1.1.0.min.js'></script>
<link type='text/css' href='css/style.css' rel='stylesheet'/>
<link type='text/css' href='css/flexslider.css' rel='stylesheet'/>
<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/bootstrap-responsive.min.css">
<script type='text/javascript' src='js/vendor/jquery-1.9.1.min.js'></script>
<script type='text/javascript' src='js/vendor/jquery.flexslider-min.js'></script>
<script type='text/javascript' src='js/vendor/jquery.mousewheel.js'></script>
<script type='text/javascript' src='js/vendor/jquery.easing.1.3.js'></script>
</head>

<body>
<script type="text/javascript">
$(window).load(function() {

    $('#carousel').show();
    $('#carousel').flexslider({
    animation: 'slide',
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 210,
    itemMargin: 5,
    asNavFor: '#slider'
  });

      $('#slider').flexslider({
      namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
    selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
      animation: "slide",
     easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
      direction: "horizontal",   //String: Select the sliding direction, 'horizontal' or 'vertical'
    reverse: false,                 //{NEW} Boolean: Reverse the animation direction
    animationLoop: false,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
    smoothHeight: true,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
      slideshow: true,                //Boolean: Animate slider automatically
      slideshowSpeed: 5000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 600,         //Integer: Set the speed of animations, in milliseconds
      initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
      randomize: false,               //Boolean: Randomize slide order
     useCSS: true,                   //{NEW} Boolean: Slider will use CSS3 transitions if available
      touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
       video: false,                   //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
      directionNav: true,             //Boolean: Create navigation for previous/next navigation? (true/false)

      controlNav: true,               //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      keyboard: true,              //Boolean: Allow slider navigating via keyboard left/right keys
      mousewheel: false,              //Boolean: Allow slider navigating via mousewheel
      prevText: "Previous",           //String: Set the text for the "previous" directionNav item
      nextText: "Next",               //String: Set the text for the "next" directionNav item
      pausePlay: false,               //Boolean: Create pause/play dynamic element
      pauseText: "Pause",             //String: Set the text for the "pause" pausePlay item
      playText: "Play",               //String: Set the text for the "play" pausePlay item
      startAt: 0,                //Integer: The slide that the slider should start on. Array notation (0 = first slide)
      pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
      pauseOnHover: true,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
      start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
    controlsContainer: "",          //Selector: Declare which container the navigation elements should be appended too. Default container is the flexSlider element. Example use would be ".flexslider-container", "#container", etc. If the given element is                                             not found, the default action will be taken.
       manualControls: "",             //Selector: Declare custom control navigation. Example would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
       // Carousel Options
    itemWidth: 0,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
    itemMargin: 10,                  //{NEW} Integer: Margin between carousel items.
    minItems: 0,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
    maxItems: 0,                    //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
    move: 0,                        //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.
    before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
      after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
      end: function(){}               //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
      });
      });
</script>
<p>
  <a class="btn btn-large btn-primary" href="index.html"><i class="icon-home icon-white"></i> Accueil   </a>
</p>
<div id="main-container">

  <div id="main" class="wrapper clearfix">

        <!-- FlexSlider -->
        <div id="container">
     <div id="slider" class="flexslider">
          <ul class="slides">
            <li>
              <img src="images/entete-menton.jpg" />
            </li>
            <li>
              <img src="images/entete-cabourg.jpg" />
            </li>
            <li>
              <img src="images/entete-meribel.jpg" />
            </li>
          </ul>
        </div>
    <div id="carousel" class="flexslider" style="display:none;">
    <ul class="slides">
            <li>
              <img src="images/entete-menton.jpg" />
            </li>
            <li>
              <img src="images/entete-cabourg.jpg" />
            </li>
            <li>
              <img src="images/entete-meribel.jpg" />
            </li>
          </ul>
</div>
  </div>
  </div> <!-- #main -->
  </div> <!-- #main-container -->
</body>
</html>
